### ISSUE TITLE
2 bugs: reversed directionality + ignored 0-lambda probability

### ISSUE THREAD

**Issue by InaMariaDeutschmann** [anthbapt/multixrank#4]
Bonjour,

I noticed two bugs with multixrank, which will impact the results obtained from the random walk.

Our multilayer network
- we have 3 monoplex (3 networks: A, B, and C) with each having only one layer
- A and B network are undirected
- C network is directed
- there are two bipartites: first connecting A with B, and a second connecting B with C
- both bipartites are undirected and not weighted

Setting up random walk with restart
- random walk probabilities are set to always start in the C network (eta = [0, 0, 1])
- the moving between monoplexes probabilities are set to always go from the C network to the B network (lambda = 1 for changing networks from C to B)
- once we are in the B network we stay there (lambda = 1 for staying in B network)
- all other lambda probabilities are set to 0
- we only have one single seed node being in the C network
- probability to restart is r = 0.7
- config.yml below

_We encountered 2 bugs_
**1. Directionality reversed**
- the C network is an edge-list with 1st column being the Source, and 2nd column being the Target
- however, the output of the random walk shows, that the direction is reversed, i.e., the code reads 1st column as Target, and 2nd column as Source

**2. Lambda probabilities**
- 1. observation: they need to be given column-wise instead of row-wise
- 2. observation: there is no test if probabilities add up to 1
- bug: Ignoring 0-probability
  + our seed node is not connected to the B network
  + we expected the random walk to stay at the seed node
  + however, the result we obtained also contained nodes from the C network that were connected to the seed node (if directionality allowed it, i.e., they were targeted by seed node)
  + from these other nodes, the random walk performed as expected and went to the B network

_Further, I have a question on the random walk result_
**specifically the random walk probability**
- when the seed node was a Target but not Source, then the random walk has no-where to go and we obtained only the seed node in random walk output (as expected)
- the random walk probability we obtained for that node was 0.7, which corresponds to the probability of restart (r=0.7)
- in this special case the random walk probability should have been 1, right?
- checking different random walk results (always having only 1 seed node), I noticed the seed node always has a random walk probability of 0.7
- is this probability computed or set directly to 0.7 for the seed node?

Thank you
Ina

_config.yml:_
```
seed:
 seeds.txt

# probability of restart
r: 0.7

# self_loops: Are self-loops allowed? 1 yes, 0 not
self_loops: 0

# eta: Restart probability for each multiplex. Must sum up to one.
eta: [0, 0, 1]

# Inter multiplex Networks Jump Probability (lambda)
lamb:
 - [0, 0, 0]
 - [0, 1, 1]
 - [0, 0, 0]

# multiplex file structure
multiplex:
 network_A:
  layers:
   - multiplex/network_A/A_edges.tsv
  graph_type: [01]
 network_B:
  layers:
   - multiplex/network_B/B_edges.tsv
  graph_type: [01]
 network_C:
  layers:
   - multiplex/network_C/C_edges.tsv
  graph_type: [11]

bipartite:
 bipartite/A2B.tsv:
  source: network_A
  target: network_B
  graph_type: 00
 bipartite/B2C.tsv:
  source: network_B
  target: network_C
  graph_type: 00
```
